Repository icecube/skymap_scanner, pull requests merged in 2023-07, with the labels that each got.

#189 Move all reco-specific logic to reco modules [minor]
  .github/workflows/tests.yml
  README.md
  requirements-all.txt
  requirements-client-starter.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  skymap_scanner/client/reco_icetray.py
  skymap_scanner/config.py
  skymap_scanner/recos/__init__.py
  skymap_scanner/recos/common/__init__.py
  skymap_scanner/recos/common/pulse_proc.py
  skymap_scanner/recos/common/vertex_gen.py
  skymap_scanner/recos/dummy.py
  skymap_scanner/recos/millipede_original.py
  skymap_scanner/recos/millipede_wilks.py
  skymap_scanner/server/start_scan.py
  skymap_scanner/utils/extract_json_message.py
  skymap_scanner/utils/prepare_frames.py
  tests/compare_scan_results.py
  tests/data/reco_pixel_pkls/get_toclient_msg_pkl.py
  tests/data/reco_pixel_pkls/millipede_wilks/BRONZE/pframe.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/BRONZE/pix.out.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/BRONZE/startup.json
  tests/data/reco_pixel_pkls/millipede_wilks/GOLD/in-ed65a85bfd0641919f6cd3df4a534bd3.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/GOLD/out-ed65a85bfd0641919f6cd3df4a534bd3.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/GOLD/pframe.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/GOLD/pixel.out.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/GOLD/startup.json
  tests/data/reco_pixel_pkls/millipede_wilks/JSON/GCDQp_packet.json
  tests/data/reco_pixel_pkls/millipede_wilks/JSON/in-18a51be2fe3e41ca97be68a84dd892df.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/JSON/out-18a51be2fe3e41ca97be68a84dd892df.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/JSON/pframe.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/JSON/pix.out.pkl
  tests/data/reco_pixel_pkls/millipede_wilks/JSON/startup.json
  tests/data/results_npz/millipede_wilks/run00127907.evt000020178442.HESE_1.npz
  tests/data/results_npz/millipede_wilks/run00136662.evt000035405932.neutrino_1.npz
  tests/data/results_npz/millipede_wilks/run00136766.evt000007637140.neutrino_1.npz
Labels: enhancement, tech debt cleanup

#206 Result Regression Error Fix
  .github/workflows/tests.yml
  .github/workflows/wipac-cicd.yml
  .gitignore
  Dockerfile
  dependencies-from-Dockerfile.log
  dependencies-from-Dockerfile_no_cvmfs.log
  dependencies-from-Dockerfile_pulsar.log
  requirements-all.txt
  requirements-client-starter.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  setup.cfg
  tests/compare_scan_results.py
Labels: bug

#207 Fix CI Dependencies
  .github/workflows/tests.yml
  .github/workflows/wipac-cicd.yml
  dependencies-from-Dockerfile_pulsar.log
Labels: bug, CI / Testing
