Repository icecube/skymap_scanner, pull requests merged in 2023-03, with the labels that each got.

#139 Fix `htcondor` Pip Install for Docker Builds
  .github/workflows/wipac-cicd.yml
  Dockerfile
Labels: bug

#142 Use `wipacdevbot` for CI Commits
  .github/workflows/wipac-cicd.yml
Labels: enhancement, CI / Testing

#143 Fix CI for Bots on `main`
  .github/workflows/tests.yml
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
Labels: CI / Testing

#144 Fix CI for Bots on `main` Pt-2
  .github/workflows/tests.yml
  .github/workflows/wipac-cicd.yml
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
Labels: bug, CI / Testing

#145 Fix CI for Bots on main Pt-3
  .github/workflows/tests.yml
  .github/workflows/wipac-cicd.yml
Labels: bug, CI / Testing

#146 Fix CI for Bots on `main` Pt-5
  .github/workflows/tests.yml
  .github/workflows/wipac-cicd.yml
Labels: bug, CI / Testing

#147 Simplification and improvement of GCD handling
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  resources/utils/save_scan_result.py
  skymap_scanner/client/reco_icetray.py
  skymap_scanner/config.py
  skymap_scanner/recos/dummy.py
  skymap_scanner/recos/millipede_original.py
  skymap_scanner/recos/millipede_wilks.py
  skymap_scanner/server/choose_new_pixels_to_scan.py
  skymap_scanner/server/start_scan.py
  skymap_scanner/utils/extract_json_message.py
  skymap_scanner/utils/load_scan_state.py
  skymap_scanner/utils/prepare_frames.py
  skymap_scanner/utils/utils.py
Labels: enhancement, cleanup

#153 SkyDriver Alpha Updates Pt-1
  skymap_scanner/server/start_scan.py
Labels: bug, enhancement

#154 CI Expediate Steps on `main`
  .github/workflows/wipac-cicd.yml
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
Labels: CI / Testing

#156 Reporter: Split Out & Refigure "Prior Processing" Time
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  skymap_scanner/client/reco_icetray.py
  skymap_scanner/server/reporter.py
  skymap_scanner/server/start_scan.py
  tests/compare_reco_pixel_pkl.py
  tests/convert_pkl.py
  tests/data/reco_pixel_pkls/BRONZE/1660761104.474899.out.pkl
  tests/data/reco_pixel_pkls/GOLD/1660761707.623653.out.pkl
  tests/data/reco_pixel_pkls/JSON/1660759716.46013.out.pkl
Labels: enhancement
