Repository icecube/skymap_scanner, pull requests merged in 2023-05, with the labels that each got.

#183 Enable HTChirp [minor]
  requirements-all.txt
  requirements-client-starter.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
Labels: dependencies

#184 Trim Logging of Large Objects
  requirements-all.txt
  requirements-client-starter.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  skymap_scanner/server/collector.py
  skymap_scanner/server/reporter.py
Labels: enhancement

#192 Decouple spline staging from class declaration
  requirements-all.txt
  requirements-client-starter.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  skymap_scanner/client/reco_icetray.py
  skymap_scanner/recos/__init__.py
  skymap_scanner/recos/dummy.py
  skymap_scanner/recos/millipede_original.py
  skymap_scanner/recos/millipede_wilks.py
Labels: enhancement, prod concern
