Repository icecube/skymap_scanner, pull requests merged in 2023-04, with the labels that each got.

#169 Reco Ack-Timeout Update [minor]
  .github/workflows/tests.yml
  README.md
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  resources/client_starter.py
  resources/k8s/k8s_skydriver_worker_job.yaml
  resources/launch_scripts/docker/launch_client.sh
  resources/launch_scripts/docker/launch_server.sh
  resources/launch_scripts/k8s/pulsar/k8s_skydriver_worker_job.yaml
  resources/launch_scripts/k8s/rabbitmq/k8s_skydriver_worker_job.yaml
  skymap_scanner/server/reporter.py
Labels: enhancement

#168 Configuration parameter for pulse series name
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  skymap_scanner/config.py
  skymap_scanner/recos/millipede_original.py
  skymap_scanner/recos/millipede_wilks.py
  skymap_scanner/server/start_scan.py
  skymap_scanner/utils/extract_json_message.py
  skymap_scanner/utils/prepare_frames.py
Labels: enhancement

#177 Fix SkyDriver URLs
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  resources/client_starter.py
  resources/utils/plot_skydriver_scan_result.py
  skymap_scanner/server/reporter.py
  skymap_scanner/server/utils.py
Labels: skydriver

#178 Migrate Files to `skyreader` & `skywriter` [minor]
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  resources/utils/i3_to_json.py
  resources/utils/keycloak_token.py
  resources/utils/make_plots.sh
  resources/utils/plot_skydriver_scan_result.py
  resources/utils/save_scan_result.py
  setup.cfg
  skymap_scanner/server/reporter.py
  skymap_scanner/server/start_scan.py
  skymap_scanner/utils/event_tools.py
  skymap_scanner/utils/extract_json_message.py
  skymap_scanner/utils/load_scan_state.py
  skymap_scanner/utils/plotting_tools.py
  skymap_scanner/utils/scan_result.py
  skymap_scanner/utils/to_skyscan_result.py
  tests/compare_reco_pixel_pkl.py
  tests/compare_scan_results.py
Labels: dependencies

#181 Remove GCP Intall Extra
  requirements-all.txt
  requirements-client-starter.txt
  requirements-gcp.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  setup.cfg
Labels: cleanup, dependencies

#180 Report First Reco Time Stats
  skymap_scanner/config.py
  skymap_scanner/server/reporter.py
Labels: enhancement

#182 EWMS Pilot Updates
  .github/workflows/tests.yml
  README.md
  requirements-all.txt
  requirements-client-starter.txt
  requirements-nats.txt
  requirements-pulsar.txt
  requirements-rabbitmq.txt
  requirements.txt
  resources/client_starter.py
  resources/k8s/k8s_skydriver_worker_job.yaml
  resources/launch_scripts/docker/launch_client.sh
  resources/launch_scripts/docker/launch_server.sh
  resources/launch_scripts/k8s/pulsar/k8s_skydriver_worker_job.yaml
  resources/launch_scripts/k8s/rabbitmq/k8s_skydriver_worker_job.yaml
  skymap_scanner/client/client.py
Labels: dependencies
